name: resource-potentials
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - numpy=1.13.3
  - pandas=0.20.3
  - matplotlib=2.1.0
  - seaborn=0.8.1
  - pandoc=1.19.2.1
  - pytest=3.2.3
  - click=6.7
  - ipython
  - fiona=1.7.11
  - rasterio=0.36.0
  - rasterstats=0.12.0
  - geopandas=0.3.0
  - requests=2.18.4
  - requests-cache=0.4.13
  - snakemake=4.4.0
  - pip:
      - pytest-pythonpath # adds the root path "./" to PYTHONPATH
      - pandoc-tablenos
      - pandoc-fignos
      - pantable
      - pycountry
