name: resource-potentials
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - numpy=1.13.3
  - pandas=0.23.2
  - gdal=2.2
  - matplotlib=2.2
  - seaborn=0.8.1
  - pandoc=2.1.1
  - pytest=3.2.3
  - click=6.7
  - ipython
  - fiona=1.7.11
  - rasterio=0.36.0
  - rasterstats=0.12.0
  - geopandas=0.3.0
  - snakemake=4.4.0
  - xlrd=1.1.0
  - descartes=1.1
  - salib=1.1.2
  - pip:
      - pytest-pythonpath # adds the root path "./" to PYTHONPATH
      - pandoc-tablenos
      - pandoc-fignos
      - pantable
      - pycountry
