name: possibility-for-electricity-autarky
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - gdal
  - matplotlib
  - seaborn
  - click
  - ipython
  - fiona
  - rasterio
  - rasterstats
  - geopandas
  - snakemake-minimal
  - xlrd
  - descartes
  - xarray
  - pip
  - pycountry
